### ISSUE TITLE
Startup error on new install

### ISSUE THREAD

**Issue by alanb128** [alanb128/ultimate-noise-box#1]
```
controller  Found seesaw supported product 4991
 controller  Starting...
 controller  init display
 controller  Error accessing splash.jpg - using default splash screen instead.
 controller  Traceback (most recent call last):
 controller    File "controller.py", line 470, in <module>
 controller      init_controller()
 controller    File "controller.py", line 203, in init_controller
 controller      lib_setup()
 controller    File "controller.py", line 150, in lib_setup
 controller      i = Image.open(ASSET_PATH + "vol_" + "{:0>3}".format(v * 5) + ".jpg")
 controller    File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 3068, in open
 controller      fp = builtins.open(filename, "rb")
 controller  FileNotFoundError: [Errno 2] No such file or directory: '/data/my_data/assets/vol_000.jpg'
```

**Comment by alanb128** [comment]
Fixed, added jpg files to repo.
